"use client";
import "./globals.css";
import { Mulish } from "next/font/google";
import Header from "./components/Header";
import { Provider } from "react-redux";
import store from "../../store";
import Footer from "./components/Footer";

const mulish = Mulish({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body>
        <Provider store={store}>
          <Header />
          {children}
        </Provider>
        <Footer />
      </body>
    </html>
  );
}
